version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/xfeatures-auth-api"
    schedule:
      interval: "weekly"
    groups:
      api-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/xfeatures-account-web"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
        versions: [ ">= 10.0.0" ]
    groups:
      web-dependencies:
        patterns:
          - "*"